### ISSUE TITLE
[BUG] 'Device unavailable' of receiver after succesfull finding

### ISSUE THREAD

**Issue by kruimel0** [lucasvdh/com.yamaha.receiver#12]
### Describe the bug
A clear and concise description of the bug.

Hi Lucas :)

After installing the 'beta' app (either upgrade from existing version or fresh install), finding my Yamaha receiver (RX-V575) works as expected. However, immediately afterwards, the receiver becomes unavailable. The receiver cannot be addressed by Homey anymore and remains as 'device unavailable' forever.

Interestingly, a downgrade from the beta app to the current published version (the last one I updated on the official athom app store), keeps the receiver in an unvailable state. This happens without re-finding of the receiver and with re-finding of the receiver. Only after a fresh install of the current non-beta branch I was able to control the receiver again.

### Steps to Reproduce the Problem

  1. Have a RX-V575 receiver working in Homey on the 0.3.4 app version
  2. Install the 0.3.6 version
  3. Observe the unavailability of the receiver both before and after re-addition of the receiver.

**Comment by lucasvdh** [comment]
Hi @kruimel0 this is probably an issue with the mapping of the fields. 

The app sets a device as unavailable when "something" in a status update call fails. I think I'll need to make a distinction between an error as a result of the device being unavailable and as a result of an error in the code.

I have some time this weekend, I'll try and look at this issue then as well.

**Comment by lucasvdh** [comment]
Can you maybe provide me with the XML response of the following post call:

```
curl 'http://192.168.x.x/YamahaRemoteControl/ctrl' \
 --request POST \
 --data '<YAMAHA_AV cmd="GET"><Main_Zone><Basic_Status>GetParam</Basic_Status></Main_Zone></YAMAHA_AV>'
```

And if you have the option, also this post call when the input is set to one of the following: 
- `USB`
- `iPod_USB`
- `Spotify`
- `NET_RADIO`
- `SERVER`
- `Tuner`
- `AirPlay`

```
curl 'http://127.0.0.1/YamahaRemoteControl/ctrl' \
 --request POST \
 --data '<YAMAHA_AV cmd="GET"><REPLACE_WITH_ZONE><Play_Info>GetParam</Play_Info></REPLACE_WITH_ZONE></YAMAHA_AV>'
```
_Note: replace `REPLACE_WITH_ZONE` with one of the values from the list._

**Comment by lucasvdh** [comment]
@kruimel0 there's a new beta version on it's way. 

I removed a lot of error suppression, so if something goes wrong now the entire app should crash giving me a nice crash report and some more insight in the issue.

**Comment by kruimel0** [comment]
@lucasvdh Didn't have too much time past days, but I did just install the new beta version from the app store. This appears to fix all issues. I had to re-install the device on Homey, but that's to be expected I guess.

Thanks!
