### ISSUE TITLE
[BUG] not available after installation, speaker ISX 80

### ISSUE THREAD

**Issue by bart973** [lucasvdh/com.yamaha.receiver#17]
After installation of the new version of the app.

My speaker ISX80 can no longer be controlled.

I reinstalled several times, the app and de speaker.

Do you know a solution?

**Comment by lucasvdh** [comment]
Hi @bart973 thanks for reporting this issue. 

I've got two questions:
1. Is the ISX80 a MusicCast device?
2. Is your device found via auto discovery or do you manually enter the IP when adding it?


Before I'm able to debug your issue I need some more information. 

The easiest solution is to provide me a diagnostic report. To get a good idea of what's going on please follow these steps:
- Restart(or reinstall) the app
- Add your device
- [Provide me a diagnostic report id](https://support.athom.com/hc/en-us/articles/360013177034-How-do-I-create-a-Diagnostics-Report-ID-).

**Comment by bart973** [comment]
1. Yes it is a Music cast speaker. Please look into this site:
https://nl.yamaha.com/nl/products/audio_visual/interior_audio/restio/isx-80.html
2. The device found via auto discovery. 

Diagnostic Report:
82c1baf0-ca53-4106-b0b9-21318fcad775

I hope you can help me.

Met vriendelijke groet,

Bart

**Comment by lucasvdh** [comment]
Thanks @bart973, I think I've narrowed down the issue. I'll let you know if I make any progress or if there's a new version for you to test.

> For my own reference:
> Issue ID: 845844
> Event ID: cf233cfa9ea94dbcbf1aa2c686d735ac

**Comment by bart973** [comment]
Tanks for the new update!!!
Working fine now! 👍👍

**Comment by lucasvdh** [comment]
You're welcome. I will close this issue and consider it resolved.
