### ISSUE TITLE
[BUG] Receiver not found

### ISSUE THREAD

**Issue by lucasvdh** [lucasvdh/com.yamaha.receiver#9]
### Describe the bug
The auto discovery doesn't find the RX-V3900

### Expected Behavior
The RX-V3900 should be discoverable

### Actual Behavior
The RX-V3900 is not discoverable

### Proposed solution
Add manually providing the receiver details as a fallback to the pairing process if not devices are found.

**Comment by juw2** [comment]
Hi, here is the output from: http://your.receiver.ip.address/YamahaRemoteControl/desc.xml

```xml
<scpd>
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
</scpd>
```

Br
Jonas

**Comment by juw2** [comment]
Adding a file instead with the output of the command.
[output.txt](https://github.com/lucasvdh/com.yamaha.receiver/files/3864747/output.txt)

**Comment by lucasvdh** [comment]
Thanks for the effort! 

That's a little less than I hoped for though. Could you maybe also provide the content of `http://192.168.1.3:8080/MediaRenderer/desc.xml`.

Ps. if you put the xml between two lines of triple back ticks ``` its display nicely, e.g.:
```xml
<xml></xml>
```

**Comment by juw2** [comment]
It's me that should be thanking you ;)
Well, port 8080 doesent work on RX-V3900.
Could that be the issue?
It only answers to port 80.
Do you still want the output of the new command?

**Comment by juw2** [comment]
```<?xml version="1.0" encoding="ISO-8859-1"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:ms="urn:microsoft-com:wmc-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device ms:X_MS_SupportsWMDRM="true">
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
<friendlyName>RX-V3900</friendlyName>
<manufacturer>YAMAHA CORPORATION</manufacturer>
<manufacturerURL>http://www.global.yamaha.com/</manufacturerURL>
<modelDescription>Network Receiver</modelDescription>
<modelName>RX-V3900</modelName>
<modelNumber>3900</modelNumber>
<modelURL>http://www.global.yamaha.com/products/av/index.html</modelURL>
<serialNumber>xxxxxxxx</serialNumber>
<UDN>uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</UDN>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>/Icons/48x48.png</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
<SCPDURL>/RenderingControl/desc.xml</SCPDURL>
<controlURL>/RenderingControl/ctrl</controlURL>
<eventSubURL>/RenderingControl/event</eventSubURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<SCPDURL>/ConnectionManager/desc.xml</SCPDURL>
<controlURL>/ConnectionManager/ctrl</controlURL>
<eventSubURL>/ConnectionManager/event</eventSubURL>
</service>
<service>
<serviceType>urn:yamaha-com:service:YamahaRemoteControl:2</serviceType>
<serviceId>urn:yamaha-com:serviceId:YamahaRemoteControl</serviceId>
<SCPDURL>/YamahaRemoteControl/desc.xml</SCPDURL>
<controlURL>/YamahaRemoteControl/ctrl</controlURL>
<eventSubURL>/YamahaRemoteControl/event</eventSubURL>
</service>
</serviceList>
<presentationURL>http://192.168.1.xx/</presentationURL>
</device>
</root>
```

**Comment by juw2** [comment]
But this is against port 80...

**Comment by lucasvdh** [comment]
I'll look into it soon.

**Comment by lucasvdh** [comment]
@juw2 the issue that you can't add your receiver should be fixed by:
https://github.com/lucasvdh/com.yamaha.receiver/releases/tag/v0.3.6
You can install the latest version via:
https://homey.app/nl-nl/app/martens.yamaha/Yamaha-versterker/test/

I will leave this issue open because the original issue that your receiver is not found through auto-discovery is still not fixed.

**Comment by juw2** [comment]
Well, I get this with the new version.
connect EHOSTUNREACH 192.168.1.173:7676

**Comment by juw2** [comment]
Removed my previous post since after reinstallation of the app I dont get the same error.
But now, if I put in the IP address and press search I get: 
An error occured

**Comment by lucasvdh** [comment]
@juw2 did you install the app via the store or manually? The reason I ask is because that was an error that I got in a previous version. Nevertheless I'll try and figure out what happened.

Is possible for you/do you know how to run a nodejs test script from the command line? This would help me to get some more debug data and solve these issues faster. It's not the end of the world if you don't it'll probably just take a bit longer to resolve.

**Comment by juw2** [comment]
I have tried both the app store version anf the node.js version.
I did retry to install the old version. Works great, then tried to upgrade to your version. Still able to see the receiver and go into settings on it to add ip but doesen't work.
If I then remove it, it can't be found and I can't add it.
Seems like the new code can't handle rx-v3900...

**Comment by juw2** [comment]
The newer releases finds my receiver without problems and can add it but after that it doesn't work.
In what file, in this project, do you run the check against the receiver?
Also, would you like me to test something or run some scripts?

**Comment by lucasvdh** [comment]
@juw2 the first stable version after of this app has just been published. I'd suggest you try adding your receiver again. 

There's been so many changes that this issue doesn't really apply to the current version that's why I will close this issue. If you're still experiencing problems in the new version I'd suggest you open a new issue.
